/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module lab2 (
  input D1,
  input D0,
  output G,
  output F,
  output E,
  output D,
  output C,
  output B,
  output A,
  output [7:0] AN
);
  assign B = 1'b0;
  assign AN[0] = 1'b0;
  assign AN[1] = 1'b1;
  assign AN[2] = 1'b1;
  assign AN[3] = 1'b1;
  assign AN[4] = 1'b1;
  assign AN[5] = 1'b1;
  assign AN[6] = 1'b1;
  assign AN[7] = 1'b1;
  assign F = ~ (D0 & D1);
  assign E = (~ D0 | D1);
  assign D = ~ (D0 ^ D1);
  assign C = (~ D1 & D0);
  assign A = ~ (D0 ^ D1);
  assign G = ~ (D0 | D1);
endmodule
