/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module lab3 (
  input C,
  input B,
  input A,
  output F
);
  assign F = ((A & ~ B & ~ C) | (~ A & ~ B & C) | (A & B & C) | (~ A & B & ~ C));
endmodule
