# -*- coding: utf-8 -*-
"""emirasal_q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14XAUnVplaNyD2gOFBp0n6vD9kEtrdjcw
"""

import random

Player1 = 0
for i in range(0,32):
  dice = random.randint(1,6)
  Player1 += dice
print("score 1:", Player1)
if Player1 == 121:
  print("Player 1 wins!")
elif Player1 > 121:
  print("Player 2 wins!")
else:
  Player2 = 0
  for i in range(0,32):
    dice = random.randint(1,6)
    Player2 += dice
  print("score 2:", Player2)
  if Player2 == 121:
    print("Player 2 wins!")
  elif Player2 > 121:
    print("Player 1 wins!")
  elif Player1 > Player2:
    print("Player 1 wins!")
  elif Player2 > Player1:
    print("Player 2 wins!")
  else:
    print("There is a tie!")