# -*- coding: utf-8 -*-
"""emirasal_q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yClpVS-uSEYlFxp42qaO0CBoUJJrSiBg
"""

number_of_credits = int(input("Please enter the number of credits earned: "))

if number_of_credits < 30:
  print("Freshman")
elif number_of_credits < 60:
  print("Sophomore")
elif number_of_credits < 90:
  print("Junior")
else:
  print("Senior")