# -*- coding: utf-8 -*-
"""emirasal_q7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OTrIsTqYZ6228l-27xTx55ohLPJ2gSix
"""

def sum_sections(courseEnroll):
  d = {}
  for course in courseEnroll:
    course_name = course[:-1]
    if course_name not in d:
      d[course_name] = courseEnroll[course]
    else:
      d[course_name] += courseEnroll[course]
  print(d)


courseEnroll = {"IF100A":262, "IF100B":212, "IF100C":248, 
                "SPS102A":263, "NS102A":64, "NS102B":52, 
                "MATH101A":236, "SPS101A":360, "HIST191A":304, 
                "MATH101B":209, "MATH101C":213, "HIST191B":264, 
                "NS102C":68, "SPS101B":385, "NS102D":69, "HIST191Y":83}

sum_sections(courseEnroll)