# -*- coding: utf-8 -*-
"""emirasal_q5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16TsFsFLTbZ5w3BVCM7a05xcVqW7papFS
"""

def indices(nums, target):
  check_list = []
  for i in range(len(nums)):
    current_number = nums[i]
    for x in range(len(nums)):
      sums = nums[i] + nums[x]
      pair = i, x
      if sums == target and i != x and pair not in check_list:
        print(pair)
        for_checking = x, i
        check_list.append(for_checking)


nums = [9,7,11,1,2,8,2,5]
target = 10
indices(nums, target)