# -*- coding: utf-8 -*-
"""emirasal_q6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wEU1oYb_fKp6BCu978ib2TfktiBXcBha
"""

group = input("Please enter your group: ").lower()

infile = open("vaccine.txt", "r")
for line in infile:
  new_line = line.strip()
  seperated = new_line.split(",")
  stage = seperated[0]
  groups = seperated[1].lower()
  order = seperated[2]
  if group == groups:
    print ("Stage", stage, "Order", order)