# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TX8Tt8h8_Syd6Or_YOSeFeaK3RrbYEIV
"""

line = input("Enter a line: ")
name = ""
while line != "end":
  name = name + line[0]
  line = input("Enter a line: ")

print(name)