# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ukEgHhIlIG-oyRlT4LKUCXRhoW2z3Yu
"""

day = input("Enter day: ")
time = input("Enter time: ")
splitted_time = time.split(":")
print(splitted_time)

if day == "Friday" and 5 > splitted_time[0] >= 21:
  print("Not allowed")
elif day == "Saturday" or day == "Sunday": 
  print("Not allowed")
elif day == "Monday" or day == "Tuesday" or day == "Wednesday" or day == "Thursday":
  if int(splitted_time[0]) < 5 or int(splitted_time[0]) >= 21:
    print("Not allowed")
  else:
    print("Allowed")  
else:
  print("Allowed")