# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lF6gwttKc8JUldD0nT6wnbPtgictZAE-
"""

data = input("Enter data: ")
country = input("Enter country ")

country1 = country.lower()
data1 = data.lower()
replaced = data1.replace(";", ":")
splitted = replaced.split(":")

if country1 in splitted and country1 != "none":
  country_index = splitted.index(country1)
  mlda_index = country_index + 1
  print(splitted[mlda_index])
else:
  print("There is no such country!")