# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lsSCt0VZ0uywYFZJ_K2idDGnLqbNAtgQ
"""

data = input("Enter input: ")
replaced = data.replace(";", ":")
splitted = replaced.split(":")

names = []
for i in range(len(splitted)):
  if splitted[i].isnumeric():
    if int(splitted[i]) > 90:
      name_index = i - 1
      print(splitted[name_index])