# -*- coding: utf-8 -*-
"""salsa20_exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VD9CR7D_k91KjkugRyGfVfI0Ezi1JBE0
"""

#!pip install pycryptodome

from Crypto.Cipher import Salsa20
import random
'''
#message = "Two things are infinite: the universe and human stupidity; and I am not sure about the universe."
message = "Kim ne derse desin, mutlu insanın en mutlu anı, uykuya daldığı andır ve mutsuz bir insanın en mutsuz anı, uykudan uyandığı andır. İnsan hayatı, bir tür hata olmalı."
ptext = message.encode('UTF-8')
print("Mesage length in bytes", len(message))
print("Mesage length in bytes", len(ptext))
#ptext = b'Two things are infinite: the universe and human stupidity; and I am not sure about the universe.'


secret = random.randint(0,2**256)
print(secret)
key = secret.to_bytes(32, byteorder='big')
print(key)


#secret = random.randint(0,2**128)
#key = secret.to_bytes(16, byteorder='big')
print("Key length in bytes", len(key))

cipher = Salsa20.new(key)
ctext = cipher.nonce + cipher.encrypt(ptext)
cipher1 = Salsa20.new(key)
ctext1 = cipher1.nonce + cipher1.encrypt(ptext)

print("plaintext: ", message)
print("ciphertext: ", ctext)
print("ciphertext1: ", ctext1)
print("Ciphertext length in bytes", len(ctext))
print("nonce: ", cipher.nonce)

ctext_nonce = ctext[:8]
ciphertext = ctext[8:]
cipher = Salsa20.new(key, nonce=ctext_nonce)
#cipher = Salsa20.new(key=secret)
dtext = cipher.decrypt(ciphertext)

print("decoded text: ", dtext.decode('UTF-8'))
print("*************************")
# Exercise
ctext = b'\xf1\xaa\xa3\xfc\x8b\x87m4\xee\x17\x10\xddE\xcd\xa7\xe7\xcb\xe6\xc5\xd8]\x9c:\xd7\x80\xc4\xa9+\x9c*\xda\x11\x03\x80M\xdf\x98A\x8b\xffvQ\xf27\xded\x9bt\xe1\x11\x81\xfc2\xa0.\x18\xe5w'
secret = 78343975280275134622484075193595221749988821779897394693788715295251789613938
key = secret.to_bytes(32, byteorder='big')

ctext_nonce = ctext[:8]
ciphertext = ctext[8:]
cipher = Salsa20.new(key, nonce=ctext_nonce)
dtext = cipher.decrypt(ciphertext)

print("decoded text: ", dtext.decode('UTF-8'))

'''