/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module CompUnsigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = a > b;
    assign \= = a == b;
    assign \< = a < b;
endmodule


module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule

module bin2seven (
	input [3:0] bin,
	output reg [6:0] seven);

	always @(bin)
	begin
		case (bin)
		4'h0 : seven = 7'b1000000;
		4'h1 : seven = 7'b1111001;
		4'h2 : seven = 7'b0100100;
		4'h3 : seven = 7'b0110000;
		4'h4 : seven = 7'b0011001;
		4'h5 : seven = 7'b0010010;
		4'h6 : seven = 7'b0000010;
		4'h7 : seven = 7'b1111000;
		4'h8 : seven = 7'b0000000;
		4'h9 : seven = 7'b0010000;
		4'hA : seven = 7'b0001000;
		4'hB : seven = 7'b0000011;
		4'hC : seven = 7'b1000110;
		4'hD : seven = 7'b0100001;
		4'hE : seven = 7'b0000110;
		4'hF : seven = 7'b0001110;
		default : seven = 7'b0000000;
		endcase
	end
endmodule

module counterBCDseven (
  input CLK,
  output A,
  output B,
  output C,
  output D,
  output E,
  output F,
  output G,
  output [7:0] AN
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire [3:0] s19;
  wire [6:0] s20;
  wire [3:0] s21;
  assign AN[0] = 1'b0;
  assign AN[1] = 1'b1;
  assign AN[2] = 1'b1;
  assign AN[3] = 1'b1;
  assign AN[4] = 1'b1;
  assign AN[5] = 1'b1;
  assign AN[6] = 1'b1;
  assign AN[7] = 1'b1;
  assign s21[0] = 1'b1;
  assign s21[1] = 1'b1;
  assign s21[2] = 1'b0;
  assign s21[3] = 1'b0;
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i0 (
    .D( s0 ),
    .C( CLK ),
    .Q( s1 ),
    .\~Q ( s2 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( s3 ),
    .C( CLK ),
    .Q( s4 ),
    .\~Q ( s5 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( s6 ),
    .C( CLK ),
    .Q( s7 ),
    .\~Q ( s8 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( s9 ),
    .C( CLK ),
    .Q( s10 ),
    .\~Q ( s11 )
  );
  CompUnsigned #(
    .Bits(4)
  )
  CompUnsigned_i4 (
    .a( s19 ),
    .b( s21 ),
    .\= ( s13 )
  );
  assign s12 = ~ s13;
  Mux_2x1 Mux_2x1_i5 (
    .sel( s1 ),
    .in_0( s4 ),
    .in_1( s5 ),
    .out( s14 )
  );
  assign s17 = (s1 & s4);
  assign s19[0] = s1;
  assign s19[1] = s4;
  assign s19[2] = s10;
  assign s19[3] = s7;
  assign s0 = (s2 & s12);
  assign s3 = (s14 & s12);
  Mux_2x1 Mux_2x1_i6 (
    .sel( s17 ),
    .in_0( s10 ),
    .in_1( s11 ),
    .out( s15 )
  );
  assign s18 = (s10 & s17);
  // bin2seven
  bin2seven bin2seven_i7 (
    .bin( s19 ),
    .seven( s20 )
  );
  assign s9 = (s15 & s12);
  Mux_2x1 Mux_2x1_i8 (
    .sel( s18 ),
    .in_0( s7 ),
    .in_1( s8 ),
    .out( s16 )
  );
  assign A = s20[0];
  assign B = s20[1];
  assign C = s20[2];
  assign D = s20[3];
  assign E = s20[4];
  assign F = s20[5];
  assign G = s20[6];
  assign s6 = (s16 & s12);
endmodule
